# STAGE 1: Build the binary
FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
# Build a statically linked binary
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# STAGE 2: Run the binary
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
# Copy only the binary from the builder stage
COPY --from=builder /app/main .

EXPOSE 8080
CMD ["./main"]